services:
  rabbitmq:
    container_name: rabbitmq
    image: "masstransit/rabbitmq"
    ports:
        - "5672:5672"
        - "15672:15672"
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  files:
  mongo_data: