name: Unit Test and Integration Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Run Unit Tests
    steps:
      - uses: actions/checkout@v2

      - name: Set Git to UTF-8
        run: git config --global core.autocrlf input

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration Debug

      - name: Run Unit Tests
        run: dotnet test --no-build --verbosity normal tests/VideoQRCode.UnitTest/

  integration-tests:
    runs-on: ubuntu-latest
    name: Run Integration Tests
    steps:
      - uses: actions/checkout@v2

      - name: Set Git to UTF-8
        run: git config --global core.autocrlf input

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration Debug

      - name: Run Integration Tests
        run: dotnet test --no-build --verbosity normal tests/VideoQRCode.IntegrationTests/
